server:
  port: 8000
spring:
  profiles:
    active: test
  cloud:
    inetutils:
      timeout-seconds: 2
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://192.168.1.6:3306/mybatis?useUnicode=true&characterEncoding=utf8
          username: root
          password: 666666
          driver-class-name: com.mysql.jdbc.Driver
        slave_1:
          url: jdbc:mysql://192.168.1.6:3306/zy1?useUnicode=true&characterEncoding=utf8
          username: root
          password: 666666
          driver-class-name: com.mysql.jdbc.Driver
        slave_2:
          url: jdbc:mysql://192.168.1.6:3306/zy2?useUnicode=true&characterEncoding=utf8
          username: root
          password: 666666
          driver-class-name: com.mysql.jdbc.Driver

  application:
    name: schoolrelation-service

mybatis:
  mapperLocations: classpath:com/zy/schoolrelation/**/*.xml
  typeAliasesPackage: com.zy.schoolrelation.map.entity
mybatis-plus:
  mapperLocations: classpath:com/zy/schoolrelation/**/*.xml
  typeAliasesPackage: com.zy.schoolrelation.map.entity
  global-config:
    db-config:
      table-prefix:


eureka:
  client:
    service-url:

      defaultZone: http://peer1:9999/eureka/

    register-with-eureka: true

    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  file: my.log
  path: var/logs
  level:
    root: info
    com.zy.schoolrelation.mp: debug

