#服务端口号
server:
  port: 8000
  ###服务名称 --注册到注册中心的服务名称
spring:
  cloud:
    inetutils:
      timeout-seconds: 2
  datasource:
    url: jdbc:mysql://192.168.1.6:3306/mybatis?useUnicode=true&characterEncoding=utf8
    username: root
    password: 666666
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  application:
    name: schoolrelation-service


mybatis:
  mapperLocations: classpath:com/zy/helloservice/**/*.xml
  typeAliasesPackage: com.zy.helloservice.dao.domain
mybatis-plus:
  mapperLocations: classpath:com/zy/helloservice/**/*.xml
  typeAliasesPackage: com.zy.helloservice.dao.domain
  global-config:
    db-config:
      ###配置全局主键策略
#      id-type: auto
      ###表名前缀配置
      table-prefix:

###eureka基本配置信息
eureka:
  client:
    service-url:
      ####当前服务的注册中心地址
      defaultZone: http://peer1:9999/eureka/
      ###需要将服务注册到eureka上
    register-with-eureka: true
    #####需要去检索服务信息
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  file: my.log
  path: var/logs
  level:
    ##root表示所有的文件，此处可以写文件所在地方，然后再写级别
    root: info
    com.zy.schoolrelation.mp: debug

