server:
  port: 8000
spring:
  cloud:
    inetutils:
      timeout-seconds: 2
  datasource:
    url: jdbc:mysql://192.168.1.6:3306/mybatis?useUnicode=true&characterEncoding=utf8
    username: root
    password: 666666
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  application:
    name: schoolrelation-service


mybatis:
  mapperLocations: classpath:com/zy/helloservice/**/*.xml
  typeAliasesPackage: com.zy.helloservice.dao.domain
mybatis-plus:
  mapperLocations: classpath:com/zy/helloservice/**/*.xml
  typeAliasesPackage: com.zy.helloservice.dao.domain
  global-config:
    db-config:
      table-prefix:


eureka:
  client:
    service-url:

      defaultZone: http://peer1:9999/eureka/

    register-with-eureka: true

    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  file: my.log
  path: var/logs
  level:
    root: info
    com.zy.schoolrelation.mp: debug

