#server.port=9001
spring:
  datasource:
    url: jdbc:mysql://192.168.1.6:3306/mybatis?useUnicode=true&characterEncoding=utf8
    username: root
    password: 666666
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  application:
    name: hello-service
  ###热部署
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录,添加那个目录的文件需要restart
      additional-paths: hello-service/src/main/java
      exclude: WEB-INF/**
mybatis:
  mapperLocations: classpath:com/zy/helloservice/**/*.xml
  typeAliasesPackage: com.zy.helloservice.dao.domain
mybatis-plus:
  mapperLocations: classpath:com/zy/helloservice/**/*.xml
  typeAliasesPackage: com.zy.helloservice.dao.domain
  global-config:
    db-config:
      ###配置全局主键策略
      id-type: auto
      ###表名前缀配置
      table-prefix:


eureka:
  client:
    service-url:
      defaultZone: http://peer1:8888/eureka/

  ####用于定义服务续约任务的调用间隔时间，默认30秒
  instance:
    #没隔30秒向注册中心发送一次心跳，心跳30秒一次
    lease-renewal-interval-in-seconds: 30
    ####用来定义服务失效的时间，默认90秒，90秒内没心跳就表示服务失效
    lease-expiration-duration-in-seconds: 90
logging:
  file: my.log
  path: /var/logs
  level:
    ##root表示所有的文件，此处可以写文件所在地方，然后再写级别
    root: info
    com.zy.helloservice.dao: debug